[package]
name = "ruscadb-node"
description = "Bindings Node.js de RuscaDB (napi-rs)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ruscadb-ffi = { workspace = true }
