[package]
name = "ruscadb-storage"
description = "Adapter de almacenamiento de RuscaDB (buffer pool LRU-K + paged file)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ruscadb-core = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
tempfile = { workspace = true }
