[package]
name = "ruscadb-storage"
description = "Adapter de almacenamiento columnar de RuscaDB (Lance/Arrow)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ruscadb-core = { workspace = true }
