[package]
name = "ruscadb"
description = "Fachada y composition root de RuscaDB."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
readme = "../../README.md"
keywords = ["database", "embedded", "vector", "graph", "multimodal"]
categories = ["database", "database-implementations", "data-structures"]

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
ruscadb-core = { workspace = true }
ruscadb-storage = { workspace = true }
ruscadb-query = { workspace = true }
ruscadb-vector = { workspace = true }
ruscadb-graph = { workspace = true }
ruscadb-multimodal = { workspace = true }
ruscadb-ai = { workspace = true }
ruscadb-wal = { workspace = true }
ruscadb-crypto = { workspace = true }
postcard = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
proptest = { workspace = true }
rstest = { workspace = true }
pretty_assertions = { workspace = true }
