[package]
name = "ruscadb-graph"
description = "Almacén de grafo de RuscaDB (adyacencia CSR + traversal)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ruscadb-core = { workspace = true }
