[package]
name = "ruscadb-query"
description = "Motor de consultas de RuscaDB (DataFusion + dialecto extendido)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ruscadb-core = { workspace = true }
