[package]
name = "ruscadb-py"
description = "Bindings Python de RuscaDB (PyO3)."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
ruscadb-ffi = { workspace = true }
